# Generated by Django 4.0.7 on 2022-09-27 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('uwinId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('department', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(max_length=100)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('topics', models.JSONField(default=list)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('isTeams', models.BooleanField(default=False)),
                ('isMultiple', models.BooleanField(default=False)),
                ('uwinId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
        ),
    ]
