# Generated by Django 4.0.7 on 2022-09-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='topics',
        ),
        migrations.AddField(
            model_name='query',
            name='topics',
            field=models.ManyToManyField(to='api.topic'),
        ),
    ]
