# Generated by Django 4.0.7 on 2022-09-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_query_topics_query_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='location',
            field=models.CharField(default='BBCafe', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='topics',
            field=models.ManyToManyField(related_name='majorTopics', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='query',
            name='uwinId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultyDetails', to='api.faculty'),
        ),
    ]
