# Generated by Django 4.0.7 on 2022-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_faculty_id_alter_faculty_uwin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='uwin_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
