# Generated by Django 4.0.7 on 2022-09-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_faculty_uwin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='query',
            name='Faculty',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
            preserve_default=False,
        ),
    ]
