openapi: 3.0.1

info:
  title: Flow-App API
  description: Endpoints for flow-app API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  
servers:
- url: http://localhost:8000/
- url: https://localhost:8000/

tags:
- name: hello
  description: API for pinging to server
- name: topic
  description: API for topics
- name: faculty
  description: API for faculty
- name: post
  description: API for queries from BBCafe


paths:
  /hello:
    $ref: "./path/hello.yaml"

  /topic:
    $ref: "./path/topic.yaml"
  
  /topic/{id}:
    $ref: "./path/topic{}.yaml"
  
  # /faculty:0
  #   get:
  #     tags:
  #     - topic
  #     summary: get all topics
  #     parameters:
  #     - name: offset
  #       in: query
  #       description: The number of items to skip before starting to collect the result
  #         set
  #       schema:
  #         type: integer
  #     - name: limit
  #       in: query
  #       description: The numbers of items to return.
  #       schema:
  #         type: integer
  #     - name: uwinID
  #       in: query
  #       description: unique identifier
  #       schema:
  #         type: string
  #     - name: firstName
  #       in: query
  #       description: first name of faculty
  #       schema:
  #         type: string
  #     - name: lastName
  #       in: query
  #       description: last name of faculty
  #       schema:
  #         type: string
  #     - name: department
  #       in: query
  #       description: department
  #       schema:
  #         type: string
  #     - name: faculty
  #       in: query
  #       description: department
  #       schema:
  #         type: string
  #     - name: email
  #       in: query
  #       description: email of faculty
  #       schema:
  #         type: string
  #     responses:
  #       200:
  #         description: list of faculty
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: object
  #                 allOf:
  #                 - type: object
  #                   properties: {}
  #                 - $ref: '#/components/schemas/topic'
  #                 - $ref: '#/components/schemas/count'
  #       400:
  #         description: sanitization error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/sanitizationerror'
  #       422:
  #         description: db error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/dberror'
  #   post:
  #     tags:
  #     - faculty
  #     summary: add new topic
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             required:
  #             - email
  #             - uwinID
  #             type: object
  #             properties:
  #               uwinID:
  #                 type: string
  #                 description: uwinID from university
  #               firstName:
  #                 type: string
  #                 description: first name of faculty member
  #               lastName:
  #                 type: string
  #                 description: last name of faculty member
  #               department:
  #                 type: string
  #                 description: department of faculty member
  #               faculty:
  #                 type: string
  #                 description: faculty
  #               email:
  #                 type: string
  #                 description: email of faculty member
  #       required: false
  #     responses:
  #       200:
  #         description: list of faculty
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/faculty'
  #       400:
  #         description: sanitization error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/sanitizationerror'
  #       422:
  #         description: db error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/dberror'
  #     x-codegen-request-body-name: faculty body
  # /faculty/{uwinID}:
  #   get:
  #     tags:
  #     - faculty
  #     summary: Get unique faculty
  #     parameters:
  #     - name: uwinID
  #       in: path
  #       description: unique id mapped to db
  #       required: true
  #       schema:
  #         type: string
  #     responses:
  #       200:
  #         description: retrieve unique faculty
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/faculty'
  #       400:
  #         description: sanitization error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/sanitizationerror'
  #       422:
  #         description: db error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/dberror'
  #   put:
  #     tags:
  #     - faculty
  #     summary: update faculty
  #     parameters:
  #     - name: uwinID
  #       in: path
  #       description: unique id mapped to db
  #       required: true
  #       schema:
  #         type: string
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             required:
  #             - email
  #             - uwinID
  #             type: object
  #             properties:
  #               uwinID:
  #                 type: string
  #                 description: uwinID from university
  #               firstName:
  #                 type: string
  #                 description: first name of faculty member
  #               lastName:
  #                 type: string
  #                 description: last name of faculty member
  #               department:
  #                 type: string
  #                 description: department of faculty member
  #               faculty:
  #                 type: string
  #                 description: faculty
  #               email:
  #                 type: string
  #                 description: email of faculty member
  #       required: false
  #     responses:
  #       200:
  #         description: updated unique faculty
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/faculty'
  #       400:
  #         description: sanitization error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/sanitizationerror'
  #       422:
  #         description: db error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/dberror'
  #     x-codegen-request-body-name: faculty body
  #   delete:
  #     tags:
  #     - faculty
  #     summary: delete faculty
  #     parameters:
  #     - name: uwinID
  #       in: path
  #       description: unique id mapped to db
  #       required: true
  #       schema:
  #         type: string
  #     responses:
  #       200:
  #         description: deleted unique faculty
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/faculty'
  #       400:
  #         description: sanitization error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/sanitizationerror'
  #       422:
  #         description: db error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/dberror'
components:
  schemas:
    count:
      type: object
      properties:
        _count:
          type: integer
          description: number of queries linked

    faculty:
      type: object
      properties:
        uwinID:
          type: string
          description: uwinID from university
        firstName:
          type: string
          description: first name of faculty member
        lastName:
          type: string
          description: last name of faculty member
        department:
          type: string
          description: department of faculty member
        faculty:
          type: string
          description: faculty
        email:
          type: string
          description: email of faculty member
      
  parameters:
    id:
      name: id
      in: query
      description: unique identifier
      schema:
        type: integer
    firstName:
      name: firstName
      in: query
      description: first name of faculty
      schema:
        type: string
    lastName:
      name: lastName
      in: query
      description: last name of faculty
      schema:
        type: string
    department:
      name: department
      in: query
      description: department
      schema:
        type: string
    faculty:
      name: faculty
      in: query
      description: department
      schema:
        type: string
    email:
      name: email
      in: query
      description: email of faculty
      schema:
        type: string
    pathId:
      name: id
      in: path
      description: unique id mapped to db
      required: true
      schema:
        type: integer
    pathUwinID:
      name: uwinID
      in: path
      description: unique id mapped to db
      required: true
      schema:
        type: string
        
  requestBodies:
    topicBody:
      content:
        application/json:
          schema:
            required:
            - topic
            type: object
            properties:
              topic:
                type: string
                description: name of topic
      required: false

    facultyBody:
      content:
        application/json:
          schema:
            required:
            - email
            - uwinID
            type: object
            properties:
              uwinID:
                type: string
                description: uwinID from university
              firstName:
                type: string
                description: first name of faculty member
              lastName:
                type: string
                description: last name of faculty member
              department:
                type: string
                description: department of faculty member
              faculty:
                type: string
                description: faculty
              email:
                type: string
                description: email of faculty member
      required: false
