# Generated by Django 4.1.2 on 2022-10-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='parent_topic',
            new_name='tag',
        ),
    ]
